# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'commit_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_commit(object):
    def setupUi(self, commit):
        commit.setObjectName("commit")
        commit.resize(451, 363)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(commit)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.textEdit_commit = QtWidgets.QTextEdit(commit)
        self.textEdit_commit.setObjectName("textEdit_commit")
        self.verticalLayout.addWidget(self.textEdit_commit)
        spacerItem = QtWidgets.QSpacerItem(20, 17, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.pushButton_cancel = QtWidgets.QPushButton(commit)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_cancel.sizePolicy().hasHeightForWidth())
        self.pushButton_cancel.setSizePolicy(sizePolicy)
        self.pushButton_cancel.setObjectName("pushButton_cancel")
        self.horizontalLayout.addWidget(self.pushButton_cancel)
        self.pushButton_commit = QtWidgets.QPushButton(commit)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_commit.sizePolicy().hasHeightForWidth())
        self.pushButton_commit.setSizePolicy(sizePolicy)
        self.pushButton_commit.setObjectName("pushButton_commit")
        self.horizontalLayout.addWidget(self.pushButton_commit)
        self.horizontalLayout.setStretch(0, 2)
        self.horizontalLayout.setStretch(1, 1)
        self.horizontalLayout.setStretch(2, 1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout.setStretch(0, 4)
        self.verticalLayout.setStretch(2, 1)
        self.horizontalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(commit)
        QtCore.QMetaObject.connectSlotsByName(commit)

    def retranslateUi(self, commit):
        _translate = QtCore.QCoreApplication.translate
        commit.setWindowTitle(_translate("commit", "commit"))
        self.pushButton_cancel.setText(_translate("commit", "取消"))
        self.pushButton_commit.setText(_translate("commit", "提交"))
